version: '3.8'

services:
  app:
    build: .
    volumes:
      - db-data:/app/
      - media-data:/app/media
    networks:
      - internal_network

  wetty:
    image: wettyoss/wetty
    restart: unless-stopped
    environment:
      - TERM=xterm-256color
    ports:
      - 3000:3000
    networks:
      - internal_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 7000:7000
    depends_on:
      - app
      - wetty
    restart: always
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  db-data:
  media-data: 
