services:
  app:
    build: .
    networks:
      - internal_network


  wetty:
    image: wettyoss/wetty
    restart: unless-stopped
    environment:
      - TERM=xterm-256color
    ports:
      - 3000:3000
    networks:
      - internal_network



  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 7000:7000
    depends_on:
      - app
      - wetty
    restart: always
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
