# Generated by Django 5.0.3 on 2024-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='files/material', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='files/news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='professors',
            name='photo',
            field=models.ImageField(upload_to='files/professors_photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(upload_to='files/works', verbose_name='Файл'),
        ),
    ]
