# Generated by Django 5.0.3 on 2024-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_material_file_alter_news_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='material', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='professors',
            name='photo',
            field=models.ImageField(upload_to='professors_photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(upload_to='works', verbose_name='Файл'),
        ),
    ]
