# Generated by Django 3.2 on 2024-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professors_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Навык')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='skills',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.Skill', verbose_name='Необходимые навыки'),
        ),
    ]
