# Generated by Django 5.0.3 on 2024-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240420_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='external_link',
            field=models.CharField(max_length=150, verbose_name='Внешняя ссылка'),
        ),
    ]
