# Generated by Django 5.0.3 on 2024-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_professors_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название ресурса')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Полезный ресурс',
                'verbose_name_plural': 'Полезные ресурсы',
            },
        ),
        migrations.AlterField(
            model_name='professors',
            name='full_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Фамилия Имя Отчество'),
        ),
    ]
